### ISSUE TITLE
Boolean values in YAML lead to unexpected behaviour

### ISSUE THREAD

**Issue by namliz** [cncf/demo#115]
```
kubectl label nodes <nodename> echo=true
```

rc.yaml:

```
spec:
   nodeSelector:
      echo: true
   containers:
```

```
$ kubectl create -f rc.yaml --validate
unable to decode "rc.yaml": [pos 434]: json: expect char '"' but got char 't'
```

The same thing happens if `true` is set to `yes`. When set to anything else like `foo` it succeeds with no complaints.  Kind of surprising if you try yes first.
