### ISSUE TITLE
Proper Job fields via the REST API

### ISSUE THREAD

**Issue by namliz** [cncf/demo#22]
kubernetes/kubernetes#23599

So for historical reference, in your JSON:

> ```
>             "spec": {
>                     "autoSelector": true,
>                     ..
>              }
> ```

And also you at the top you must:

> "apiVersion": "extensions/v1beta1"

**Comment by namliz** [comment]
Your YAML would look like:

```
apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: mng
spec:
  autoSelector: true
```

Write in YAML and generate the json.
